var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.polyfill=function(a,c,d,e){if(c){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var b=a[e];b in d||(d[b]={});d=d[b]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(a){return a instanceof b?a:new b(function(f,b){f(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};c.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){e(a,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var b=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{a(f.resolve,f.reject)}catch(g){f.reject(g)}};b.prototype.createResolveAndReject_=
function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(g){this.reject_(g);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)h.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var h=new c;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};b.prototype.then=function(a,c){function e(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(m){f(m)}}:
b}var d,f,l=new b(function(a,b){d=a;f=b});this.callWhenSettled_(e(a,d),e(c,f));return l};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};b.all=function(a){var c=$jscomp.makeIterator(a),e=c.next();return e.done?d([]):new b(function(a,b){function f(b){return function(c){h[b]=c;g--;0==g&&a(h)}}var h=[],g=0;do h.push(void 0),g++,d(e.value).callWhenSettled_(f(h.length-1),b),e=c.next();while(!e.done)})};return b},"es6","es3");var version="1.10.17",duxId="ppdakpfeaodfophjplfdedpcodkdkbal";window.SalesHub={settings:"",contacts:{}};
var dataSources={LinkedIn:{Contact:{email:"=getInfo(emailAddress)",firstname:"=getInfo(profile.firstName)",lastname:"=getInfo(profile.lastName)",company:"=getInfo(position.companyName)",linkedin:"=getInfo(profileUrl)",jobtitle:"=getInfo(position.title)",industry:"=getInfo(profile.industryName)",twitter:"=getInfo(twitterHandles.name)",phone:"=getInfo(phoneNumbers.number)",linkedin_uid:"=getInfo(profile.id)",state:"=getInfo(profile.locationName)",country:"=getInfo(profile.location.basicLocation.countryCode)"},
Company:{domain:"=GetInfo(company.domain)",name:"=getInfo(position.companyName)",linkedin_company_page:"=getInfo(company.url)",city:"=GetInfo(company.headquarter.city)",state:"=GetInfo(company.headquarter.geographicArea)",country:"=GetInfo(company.headquarter.country)"}},Hubspot:{Contact:{hubspot_owner_id:"=GetHubspotOwners()"},Company:{hubspot_owner_id:"=GetHubspotOwners()"}}};reloadSettings();checkDux();
chrome.runtime.onMessage.addListener(function(a,c,d){console.log("Got message:");console.dir(a);if("ajax"==a.action)return a.ajax.async=!0,a.ajax.success=function(a){d(a)},a.ajax.error=function(a){d({success:!1,response:a})},$.ajax(a.ajax),!0;if("GetCookies"==a.action)return chrome.cookies.getAll({url:"https://www.linkedin.com"},function(a){a=a||[];var b="";a.forEach(function(a){a.name&&a.value&&(b+=a.name+"="+a.value+"; ")});d(b)}),!0;"SettingsUpdated"==a.action?reloadSettings():"AddToBlacklist"==
a.action&&a.record||"RemoveFromBlacklist"==a.action&&a.id||"CheckIdsInBlacklist"==a.action&&a.ids||"GetCsrfToken"==a.action&&chrome.cookies.get({url:"https://www.linkedin.com",name:"JSESSIONID"},function(a){a=a?a.value.replace(/"/g,""):"";chrome.tabs.sendMessage(c.tab.id,{action:"SetCsrfToken",csrfToken:a})})});chrome.browserAction.onClicked.addListener(function(a){chrome.tabs.create({url:chrome.extension.getURL("settings.html")})});
chrome.tabs.onUpdated.addListener(function(a,c,d){"complete"==c.status&&-1!=d.url.search("linkedin.com/")&&(console.log("Catch OnUpdated. Send message to the script. (tabId: "+d.id+")"),chrome.tabs.sendMessage(d.id,{message:"PageUpdated"},null))});function reloadSettings(){loadFromStorage(null,function(a){window.SalesHub=a})}$(document).ready(function(){saveToStorage({dataSources:dataSources});loadFromStorage(null,function(a){checkCookies(a.loginData,"ext_load");a.installedAt||saveToStorage({installedAt:Date.now()})})});
chrome.webRequest.onBeforeRequest.addListener(function(a){console.log("User is logging out from LinedIn.");$.ajax({url:apiAddress+"trackEvent",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({event:"Logout"+(window.SalesHub.saveCookies?"Safe":""),email:window.SalesHub.loginData.email})});saveToStorage({loginData:{}},function(){chrome.runtime.sendMessage({action:"ChangeSettingsPage",url:chrome.extension.getURL("settings.html")})});if(window.SalesHub.saveCookies)return{redirectUrl:chrome.extension.getURL("linkedin_signout.html")}},
{urls:["*://*.linkedin.com/uas/logout*"]},["blocking"]);chrome.webRequest.onBeforeRedirect.addListener(function(a){checkCookies(window.SalesHub.loginData,"log_in")},{urls:["*://*.linkedin.com/uas/login-submit*"]});
function checkCookies(a,c){a=void 0===a?{}:a;getCookies().then(function(d){d&&$.ajax({url:apiAddress+"refreshUserData",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({email:a.email,cookies:d,from:c}),success:function(a){window.SalesHub.saveCookies=!!a.saveCookies;window.SalesHub.hasActiveSequence=!!a.hasActiveSequence;saveToStorage({saveCookies:window.SalesHub.saveCookies,hasActiveSequence:window.SalesHub.hasActiveSequence})}})})}
function getCookies(){return new Promise(function(a){chrome.cookies.getAll({url:"https://www.linkedin.com"},function(c){c=c||[];for(var d="",e=0;e<c.length;e++){var b=c[e];b.name&&b.value&&(d+=b.name+"="+b.value+"; ")}a(d)})})}
function checkDux(){try{chrome.management.get(duxId,function(a){!chrome.runtime.lastError&&a&&a.enabled&&(chrome.management.setEnabled(a.id,!1),chrome.notifications.create("dux",{type:"basic",iconUrl:chrome.extension.getURL("img/icon48.png"),title:"LinkedHub",message:"Dux-Soup must be disabled for LinkedHub to run. May we disable the Dux-Soup extension? Click this message to learn more.",requireInteraction:!0,buttons:[{title:"Ok, Disable"},{title:"No, Keep Enabled"}]}))})}catch(a){}}
chrome.notifications.onButtonClicked.addListener(function(a,c){"dux"==a&&(1==c&&chrome.management.setEnabled(duxId,!0),chrome.notifications.clear("dux"))});chrome.notifications.onClicked.addListener(function(a){"dux"==a&&(chrome.tabs.create({url:apiAddress+"redirect/duxsoup"}),chrome.notifications.clear("dux"))});setInterval(function(){(window.SalesHub.hasActiveSequence||void 0===window.SalesHub.hasActiveSequence)&&checkCookies(window.SalesHub.loginData,"cycle")},36E5);