var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,f={next:function(){if(c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(a,b,c,f){if(b){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var l=a[f];l in c||(c[l]={});c=c[l]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
function completeUrl(a,b){b=void 0===b?"":b;return a&&0!=a.indexOf("http://")&&0!=a.indexOf("https://")?0==a.indexOf("?")?b.split("?",2)[0]+a:0==a.indexOf("/")?(b.match(/(https?:\/\/[^\/]+)\/?/)||[])[1]+a:b.substr(0,b.lastIndexOf("/")+1)+a:a}function insertToTextarea(a,b){var c=a.selectionStart,f=a.selectionEnd,l=a.value,p=l.substring(0,c);f=l.substring(f,l.length);a.value=p+b+f;a.selectionStart=a.selectionEnd=c+b.length}
function log(a,b){return console.log("["+(new Date).toLocaleString()+"]: ",a,b||"")}function logError(a,b){return console.error("["+(new Date).toLocaleString()+"]: ",a,b||"")}function splitOnce(a,b){a=a.split(b);var c=[a.shift()];a.length&&c.push(a.join(b));return c}
function saveToStorage(a,b){try{if(a&&a.templates){var c=Object.getOwnPropertyNames(a.templates),f;for(f=0;f<c.length;f++)a["template"+f]={name:c[f],data:a.templates[c[f]]};a["template"+f]=null;a.templates=null}}catch(l){logError(l)}finally{chrome.storage.sync.set(a,function(){chrome.runtime.sendMessage({action:"SettingsUpdated"});b&&b(chrome.runtime.lastError)})}}
function loadFromStorage(a,b){var c=a;a&&void 0!==a.templates&&(c=null);chrome.storage.sync.get(c,function(c){try{if(c&&a&&a.templates){c.templates={};for(var f=0;;){var p=c["template"+f];if(p&&p.name&&p.data)c.templates[p.name]=p.data,delete c["template"+f];else break;f++}}if(a&&c){for(var q in c)void 0===a[q]&&delete c[q];for(var d in a)void 0===c[d]&&(c[d]=a[d])}}catch(k){logError(k)}finally{b&&b(c)}})}function getElementIndex(a){for(var b=0;a=a&&a.previousElementSibling;)b++;return b}
function normalizeName(a){if("string"!=typeof a)return"";a=a.trim().replace(/(\s[^,]+),.+/g,"$1").replace(/^([^,]+,[^,]+),.+$/,"$1").replace(/^([^-]+)-.+$/,"$1").replace(/^([^\/]+)\/.+$/,"$1").replace(/\([^\(]+\)/g,"").replace(/\[[^\[]+\]/g,"").replace(/{[^{]+}/g,"").replace(/"[^"]+"/g,"").replace(/(:?\W|^)([A-Z]\.)+/g,"$1").replace(/^[!-/]+/,"").replace(/[!-/]+$/,"");for(var b="",c=0,f=a.length;c<f;c++)b+=256>a.charCodeAt(c)?a[c]:"";a=b.trim();a=parseFullName(a);return(a.first+" "+a.last).trim()}
function parseFullName(a,b,c,f,l){function p(a){if(f)throw"Error: "+a;g.error.push("Error: "+a)}function q(a,b){var c="e y av af da dal de del der di la le van der den vel von II III IV J.D. LL.M. M.D. D.O. D.C. Ph.D.".split(" "),f=[];if(b)for(f=Object.keys(g).filter(function(a){return"error"!==a}),d=0,r=f.length;d<r;d++)if(a[f[d]]){var e=(a[f[d]]+"").split(" ");k=0;for(v=e.length;k<v;k++)b=c.map(function(a){return a.toLowerCase()}).indexOf(e[k].toLowerCase()),-1<b?e[k]=c[b]:1===e[k].length?e[k]=
e[k].toUpperCase():2<e[k].length&&e[k].slice(0,1)===e[k].slice(0,1).toUpperCase()&&e[k].slice(1,2)===e[k].slice(1,2).toLowerCase()&&e[k].slice(2)===e[k].slice(2).toUpperCase()?e[k]=e[k].slice(0,3)+e[k].slice(3).toLowerCase():"suffix"!==f[k]||"."===h[k].slice(-1)||t.indexOf(h[k].toLowerCase())?e[k]=e[k].slice(0,1).toUpperCase()+e[k].slice(1).toLowerCase():e[k]===e[k].toLowerCase()&&(e[k]=e[k].toUpperCase());a[f[d]]=e.join(" ")}return a}var d,k,r,v,m,h=[],n=[null],e=[];var u="& and et e of the und y".split(" ");
var g={title:"",first:"",middle:"",last:"",nick:"",suffix:"",error:[]};b=b&&-1<"title first middle last nick suffix error".split(" ").indexOf(b.toLowerCase())?b.toLowerCase():"all";!1===c&&(c=0);!0===c&&(c=1);c="undefined"===c||0!==c&&1!==c?-1:c;!0===f&&(f=1);f=f&&1===f?1:0;!0===l&&(l=1);l=l&&1===l?1:0;if(!a||"string"!==typeof a)return p("No input"),g=q(g,c),"all"===b?g:g[b];-1===c&&(c=a===a.toUpperCase()||a===a.toLowerCase()?1:0);if(l){var t="esq esquire jr jnr sr snr 2 ii iii iv v clu chfc cfp md phd j.d. ll.m. m.d. d.o. d.c. p.c. ph.d.".split(" ");
var w="a ab antune ap abu al alm alt bab b\u00e4ck bar bath bat beau beck ben berg bet bin bint birch bj\u00f6rk bj\u00f6rn bjur da dahl dal de degli dele del della der di dos du e ek el escob esch fleisch fitz fors gott griff haj haug holm ibn kauf kil koop kvarn la le lind l\u00f6nn lund mac mhic mic mir na naka neder nic ni nin nord norr ny o ua ui' \u00f6fver ost \u00f6ver \u00f6z papa pour quarn skog skoog sten stor str\u00f6m s\u00f6der ter ter tre t\u00fcrk van v\u00e4st v\u00e4ster vest von".split(" ");
l="mr;mrs;ms;miss;dr;herr;monsieur;hr;frau;a v m;admiraal;admiral;air cdre;air commodore;air marshal;air vice marshal;alderman;alhaji;ambassador;baron;barones;brig;brig gen;brig general;brigadier;brigadier general;brother;canon;capt;captain;cardinal;cdr;chief;cik;cmdr;coach;col;col dr;colonel;commandant;commander;commissioner;commodore;comte;comtessa;congressman;conseiller;consul;conte;contessa;corporal;councillor;count;countess;crown prince;crown princess;dame;datin;dato;datuk;datuk seri;deacon;deaconess;dean;dhr;dipl ing;doctor;dott;dott sa;dr;dr ing;dra;drs;embajador;embajadora;en;encik;eng;eur ing;exma sra;exmo sr;f o;father;first lieutient;first officer;flt lieut;flying officer;fr;frau;fraulein;fru;gen;generaal;general;governor;graaf;gravin;group captain;grp capt;h e dr;h h;h m;h r h;hajah;haji;hajim;her highness;her majesty;herr;high chief;his highness;his holiness;his majesty;hon;hr;hra;ing;ir;jonkheer;judge;justice;khun ying;kolonel;lady;lcda;lic;lieut;lieut cdr;lieut col;lieut gen;lord;m;m l;m r;madame;mademoiselle;maj gen;major;master;mevrouw;miss;mlle;mme;monsieur;monsignor;mr;mrs;ms;mstr;nti;pastor;president;prince;princess;princesse;prinses;prof;prof dr;prof sir;professor;puan;puan sri;rabbi;rear admiral;rev;rev canon;rev dr;rev mother;reverend;rva;senator;sergeant;sheikh;sheikha;sig;sig na;sig ra;sir;sister;sqn ldr;sr;sr d;sra;srta;sultan;tan sri;tan sri dato;tengku;teuku;than puying;the hon dr;the hon justice;the hon miss;the hon mr;the hon mrs;the hon ms;the hon sir;the very rev;toh puan;tun;vice admiral;viscount;viscountess;wg cdr".split(";")}else t=
"esq esquire jr jnr sr snr 2 ii iii iv md phd j.d. ll.m. m.d. d.o. d.c. p.c. ph.d.".split(" "),w="ab;bar;bin;da;dal;de;de la;del;della;der;di;du;ibn;l';la;le;san;st;st.;ste;ter;van;van de;van der;van den;vel;ver;vere;von".split(";"),l="dr miss mr mrs ms prof sir frau herr hr monsieur captain doctor judge officer professor".split(" ");(m=(" "+a+" ").match(/\s(?:[\u2018\u2019']([^\u2018\u2019']+)[\u2018\u2019']|[\u201c\u201d"]([^\u201c\u201d"]+)[\u201c\u201d"]|\[([^\]]+)\]|\(([^\)]+)\)),?\s/g))&&(e=
e.concat(m));m=e.length;if(1===m)g.nick=e[0].slice(2).slice(0,-2),","===g.nick.slice(-1)&&(g.nick=g.nick.slice(0,-1)),a=(" "+a+" ").replace(e[0]," ").trim(),e=[];else if(1<m){p(m+" nicknames found");for(d=0;d<m;d++)a=(" "+a+" ").replace(e[d]," ").trim(),e[d]=e[d].slice(2).slice(0,-2),","===e[d].slice(-1)&&(e[d]=e[d].slice(0,-1));g.nick=e.join(", ");e=[]}if(!a.trim().length)return g=q(g,c),"all"===b?g:g[b];d=0;a=a.split(" ");for(r=a.length;d<r;d++){m=a[d];var x=null;","===m.slice(-1)&&(x=",",m=m.slice(0,
-1));h.push(m);n.push(x)}r=h.length;for(d=r-1;0<d;d--)if(a="."===h[d].slice(-1)?h[d].slice(0,-1).toLowerCase():h[d].toLowerCase(),-1<t.indexOf(a)||-1<t.indexOf(a+"."))e=h.splice(d,1).concat(e),","===n[d]?n.splice(d+1,1):n.splice(d,1);m=e.length;1===m?(g.suffix=e[0],e=[]):1<m&&(p(m+" suffixes found"),g.suffix=e.join(", "),e=[]);if(!h.length)return g=q(g,c),"all"===b?g:g[b];r=h.length;for(d=r-1;0<=d;d--)if(a="."===h[d].slice(-1)?h[d].slice(0,-1).toLowerCase():h[d].toLowerCase(),-1<l.indexOf(a)||-1<
l.indexOf(a+"."))e=h.splice(d,1).concat(e),","===n[d]?n.splice(d+1,1):n.splice(d,1);m=e.length;1===m?(g.title=e[0],e=[]):1<m&&(p(m+" titles found"),g.title=e.join(", "),e=[]);if(!h.length)return g=q(g,c),"all"===b?g:g[b];if(1<h.length)for(d=h.length-2;0<=d;d--)-1<w.indexOf(h[d].toLowerCase())&&(h[d]=h[d]+" "+h[d+1],h.splice(d+1,1),n.splice(d+1,1));if(2<h.length)for(d=h.length-3;0<=d;d--)-1<u.indexOf(h[d+1].toLowerCase())&&(h[d]=h[d]+" "+h[d+1]+" "+h[d+2],h.splice(d+1,2),n.splice(d+1,2),d--);n.pop();
u=n.indexOf(",");l=n.filter(function(a){return null!==a}).length;if(1<u||1<l)for(d=h.length-1;2<=d;d--)if(","===n[d])e=h.splice(d,1).concat(e),n.splice(d,1),l--;else break;e.length&&(g.suffix&&(e=[g.suffix].concat(e)),g.suffix=e.join(", "),e=[]);0<l?(1<l&&p(l-1+" extra commas found"),n.indexOf(",")&&(g.last=h.splice(0,n.indexOf(",")).join(" "),n.splice(0,n.indexOf(",")))):g.last=h.pop();if(!h.length)return g=q(g,c),"all"===b?g:g[b];g.first=h.shift();if(!h.length)return g=q(g,c),"all"===b?g:g[b];2<
h.length&&p(h.length+" middle names");g.middle=h.join(" ");g=q(g,c);return"all"===b?g:g[b]}function hashCode(a){var b=0,c;if(0===a.length)return b;for(c=0;c<a.length;c++){var f=a.charCodeAt(c);b=(b<<5)-b+f;b|=0}return b};