var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");window.SalesHub={company:{},existedContact:{},colors:{white:"#fff",green:"rgba(129, 215, 46, 0.7)",yellow:"rgba(255, 255, 0, 0.6)",red:"rgba(255, 32, 0, 0.6)"},prospectButtonTimerId:void 0,prospectButtonDelay:200};var linkedHubMutationObservers={};
function pageInit(){log("Linkedhub initialisation.");$("#saleshub_panel").remove();$("#linkedhub_add_to_sequence").remove();window.SalesHub.profileInfo={};window.SalesHub.existedContact={};chrome.runtime.sendMessage({action:"GetCsrfToken"});chrome.runtime.sendMessage("nfchanglclaenbeppcahhmoilcibnllk",{action:"AreYouInstalled"},function(a){a&&a.installed&&(window.SalesHub.newerVersionInstalled=!0)});var a="";if(-1<document.URL.indexOf("linkedin.com/in/")||-1<document.URL.indexOf("linkedin.com/sales/profile/")||
-1<document.URL.indexOf("linkedin.com/sales/people/"))a="profile";else if(-1<document.URL.indexOf("/messaging/thread/"))a="messages";else if(-1<document.URL.indexOf("linkedin.com/vsearch/p?"))a="search";else if(-1<document.URL.indexOf("linkedin.com/search/results/people/?"))a="searchNew";else return;loadFromStorage(null,function(b){Object.assign(window.SalesHub,b);window.SalesHub.defaultValues=window.SalesHub.defaultValues||{};"profile"==a?showProspectButtonWithDelay():"search"==a&&((new MutationObserver(function(a,
b){console.dir(a);b=!1;for(var c=0;c<a.length&&!b;c++)for(var d=0;d<a[c].addedNodes.length&&!b;d++)"results"==a[c].addedNodes[d].id&&(b=!0,log("results updated!"),checkPersonsInBlacklist())})).observe(document.querySelector("#results-container"),{childList:!0}),checkPersonsInBlacklist())})}
chrome.runtime.onMessage.addListener(function(a,b,c){log("Got message:");console.dir(a);"PageUpdated"===a.message?(log("PageUpdated event."),pageInit()):"CheckIdsInBlacklist"==a.action&&a.ids?showBlButtons(a.ids):"SetCsrfToken"==a.action?a.csrfToken&&(window.csrfToken=a.csrfToken):"SequencesList"==a.action&&a.sequences&&showSequencesSelector(a.sequences)});
function showSequencesSelector(a){var b='<li id="linkedhub_add_to_sequence" style="display: inline-block;vertical-align: middle;padding: 6px 0px;right: 0px;position: absolute;"><select style="display:none;"><option value="" disabled selected>Add to linkedhub sequence</option>';a.forEach&&a.forEach(function(a){a.id&&a.name&&(b+='<option value="'+a.id+'">'+a.name+"</option>")});b+="</select></li>";$("#linkedhub_add_to_sequence").remove();$(".search-results-container > ul:first").append(b);$("#linkedhub_add_to_sequence select").fadeIn(200);
$("#linkedhub_add_to_sequence select").change(function(a){chrome.runtime.sendMessage({action:"AddLinkToSequence",id:a.target.value,link:window.location.href});a.target.value="";$(a.target).fadeOut(200,function(){$(a.target).fadeIn(200)})})}
function showBlButtons(a){$(".lh-blacklist").remove();$("ol#results > li").each(function(b,c){b=a[parseInt(c.dataset.liEntityId)]?"checked":"";$(c).find(".primary-action-button").before('<label title="LinkedHub Blacklist" class="lh-blacklist switch"><input type="checkbox" '+b+'><div class="slider round"></div></label>')});$(".lh-blacklist input").change(function(a){if(a=parseInt($(this).closest("li").attr("data-li-entity-id")))if($(this).is(":checked")){var c=$(this).closest("li").find("a.title"),
b=c.text();c=c.attr("href");var e=b.indexOf(" ");chrome.runtime.sendMessage({action:"AddToBlacklist",record:{li_id:a,li_rofile_id:"",first_name:b.substr(0,e),last_name:b.substr(e+1),thread_id:null,profile_link:completeUrl(c,"https://linkedin.com/")}})}else chrome.runtime.sendMessage({action:"RemoveFromBlacklist",id:a})})}
function checkPersonsInBlacklist(){var a=[];$("ol#results > li").each(function(b,c){(b=c.dataset.liEntityId)&&a.push(parseInt(b))});chrome.runtime.sendMessage({action:"CheckIdsInBlacklist",ids:a})}
function showAddToBlacklistBtn(){$("#saleshub_container").prepend('<a href="#" id="saleshub_add_to_blacklist" target="_blank" class="button-primary saleshub_btn">Add to Blacklist</a>');$("#saleshub_add_to_blacklist").click(function(a){a.preventDefault();$(a.target).attr("disabled",!0);a=$('.profile-overview-content [id^="member-"]').prop("id").match(/-(\d+)/);var b=$(".full-name").text(),c=b.indexOf(" ");a&&a[1]&&(a=parseInt(a[1]),chrome.runtime.sendMessage({action:"AddToBlacklist",record:{li_id:a,
li_rofile_id:"",first_name:b.substr(0,c),last_name:b.substr(c+1),thread_id:null,profile_link:location.origin+location.pathname}}))})}function getGETParam(a,b){if(a&&-1<a.indexOf("?")){a=a.split("?")[1].split("&");for(var c in a){var d=a[c].split("=");if(d[0]===b)return decodeURIComponent(d[1])}}return""};