var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(m){f(m)}}:
b}var d,f,g=new e(function(a,b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return g};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
e){for(var d=$jscomp.makeIterator(a),f=d.next();!f.done;f=d.next())c(f.value).callWhenSettled_(b,e)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){g[b]=c;k--;0==k&&a(g)}}var g=[],k=0;do g.push(void 0),k++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
var MAX_CONNECT_MSG_SIZE=300,MAX_STEPS_COUNT=6,BL_REFRESH_DELAY=2E3,seqInitiated=!1,prospectorInitiated=!1,plansInitiated=!1,blFilterTimer=0,blRefreshTimerId=0,defaultSettings={version:10,emailDiscovery:[{dataSource:"LinkedIn",group:"Contact",label:"Email",hsField:"email",locked:!0}],contact:[{dataSource:"LinkedIn",group:"Contact",label:"First Name",hsField:"firstname",locked:!0},{dataSource:"LinkedIn",group:"Contact",label:"Last Name",hsField:"lastname",locked:!0},{dataSource:"LinkedIn",group:"Contact",
label:"Company Name",hsField:"company"},{dataSource:"LinkedIn",group:"Contact",label:"LinkedIn",hsField:"linkedin"},{dataSource:"LinkedIn",group:"Contact",label:"Job Title",hsField:"jobtitle"},{dataSource:"LinkedIn",group:"Contact",label:"Industry",hsField:"industry"}],company:[{dataSource:"LinkedIn",group:"Company",label:"Name",hsField:"name",locked:!0},{dataSource:"LinkedIn",group:"Company",label:"Company Domain Name",hsField:"domain",locked:!0},{dataSource:"LinkedIn",group:"Company",label:"LinkedIn Company Page",
hsField:"linkedin_company_page"}],integration:{hsPortalId:"",hsPortalAPIKey:"",emailHunterAPIKey:"",anyMailFinderAPIKey:"",findAnyEmailAPIKey:"",findThatLeadAPIKey:"",toofrAPIKey:"",briteverifyAPIKey:"",linkedInEmail:"",linkedInPassword:""},general:{bulkEnroll:!1,sendLIMessage:!1,sendEmail:!1,autoLogConversation:!0,notifyOnMessageLog:!1}},hiddenOptions={"Contact\u00b7First Name":!0,"Contact\u00b7Last Name":!0,"Contact\u00b7Email":!0,"Contact\u00b7LinkedIn Bio":!0,"Contact\u00b7Twitter Bio":!0,"Contact\u00b7Twitter Username":!0,
"Company\u00b7Name":!0,"Company\u00b7Company Domain Name":!0},pageProperties={page0:{title:"LinkedHub - Profile"},page1:{title:"LinkedHub - Sequences Cloud"}},sequenceOnScreen={_saved:!0,get saved(){return this._saved},set saved(a){this._saved=a;$("#seq_save").prop("disabled",a)},id:0,status:seqStatus.NOT_STARTED,name:"",urls:[],steps:[]},formats=["No Formatting","Lowercase","Uppercase"],limitDataSources={LinkedIn:!0};
$(document).ready(function(){window.hubspotProperties={};window.hubspotPropertiesByName={};$(window).on("hashchange",hashChangedHandler);$.MessageBoxSetup({top:"auto"});loadFromStorage({settings:"",loginData:{},dataSources:{},saveCookies:!1,version:""},function(a){if(!a.settings||!a.settings.version||a.settings.version<defaultSettings.version)a.settings&&a.settings.version&&a.settings.version<defaultSettings.version&&(defaultSettings.integration=a.settings.integration),saveToStorage({settings:defaultSettings}),
a.settings=defaultSettings;window.settings=a.settings;window.loginData=a.loginData;window.dataSources=a.dataSources;window.saveCookies=a.saveCookies;window.loginData.email&&$(".nav-block").removeClass("disabled");$.fn.select2.defaults.set("minimumResultsForSearch","13");$.fn.select2.defaults.set("placeholder","Select something");console.log("restoring settings");$(".nav-block .nav-block__item a").click(pageSelect);$(".popup_wraper .close").click(function(){$(this).closest(".popup_wraper").hide()});
$(".popup_wraper").click(function(a){this==a.target&&$(this).closest(".popup_wraper").hide()});$("#li_login").click(userSignin);$("#user_logout").click(userLogout);$("#btn_add_card").click(updateCard);$("#prospects_remain").click(subscriptionCheck);showUser();blList();$(".blacklist tbody,.blacklist thead").click(blClick);$(".bl-filter input").on("input",blFilterChange);$("#seq_create").click(seqCreate);$("#seq_save").click(seqSave);$("#seq_start").click(seqStart);$("#seq_stop").click(seqStop);$("#seq_refresh").click(seqRefreshClick);
$(".sequences tbody").click(seqClick);$("#seq_name").keyup(seqMarkUnsaved);$(".tab.seq-steps-view").click(seqStepClick);$(".tab.seq-steps-view").change(seqStepChange);$(".seq_message, .seq_connect").click(seqStepCreateClickHandler);$("#seq_edit_save").click(seqStepSave);$("#seq_log").click(seqShowLog);$("select.sel2").select2({placeholder:"Insert Tag",minimumResultsForSearch:Infinity});$("select.sel2").on("select2:select",function(a){insertToTextarea($(".step-edit__text textarea")[0],a.params.data.id);
$(".step-edit__text textarea").focus();$("select.sel2").val("").trigger("change")});$("#seq_urls").click(function(a){$(a.target).hasClass("seq-urls__item__delete")&&($(a.target).closest("li").remove(),seqMarkUnsaved())});$("#seq_urls input").keyup(function(a){13==a.keyCode&&seqAddLink()});$("a.enrollments").click(function(a){a.preventDefault();pageSelect("page0")});pageSelect(location.hash.slice(1));subscriptionCheck()})});
chrome.runtime.onMessage.addListener(function(a,b,c){log("Got message",a);"ChangeSettingsPage"==a.action&&a.url&&(window.location=a.url,window.location.reload(),a.activate&&chrome.tabs.getCurrent(function(a){chrome.tabs.update(a.id,{active:!0})}))});
function showUser(){window.loginData.email?(window.loginData.fullName?$("#tab_loggedin .loggedin_name").text(window.loginData.fullName+" ("+window.loginData.email+")"):$("#tab_loggedin .loggedin_name").text(window.loginData.email),$("#tab_signup").hide(),$("#tab_login").hide(),$("#tab_loggedin").show(),window.Intercom&&window.Intercom("boot",{app_id:"ajlejzmy",name:window.loginData.fullName,email:window.loginData.email,user_hash:window.loginData.intercomHash})):window.Intercom&&window.Intercom("boot",
{app_id:"ajlejzmy"})}function formatSelect2(a){if(a.id&&0<=a.id.indexOf("\u00b7")){var b=a.id.split("\u00b7")[0].toLowerCase();return $('<span class="select2-option-ico-'+b+'">'+a.text+"</span>")}return a.text}
function seqShowLog(a){var b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return a.preventDefault(),b=parseInt($(".sequences tr.seq-active").attr("seq-id")),d.yield(getCookies(),2);c=d.yieldResult;showLoading(!0,1);$.ajax({url:apiAddress+"getSequenceLog",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:c,id:b}),success:function(b){showLoading(!1,1);b.enrolledLastDay=b.enrolledLastDay||0;var c="",e='<b>Daily limit: </b><span class="limit'+
(b.enrolledLastDay>=window.loginData.enrollmentsPerDay?" reached":"")+'">'+b.enrolledLastDay+" of "+window.loginData.enrollmentsPerDay+"</span> new people enrolled for the last 24 hours.<br>\n",d="<b>Enrolled into the sequence:</b> "+b.sequenceEnrolled+"<br>\n",h="<b>Responded within the sequence:</b> "+b.sequenceResponded+"<br>\n";b&&b.logLines?(b.logLines.forEach(function(a){c="["+(new Date(a.time)).toLocaleString()+"] "+a.text+"<br>\n"+c}),c=c?"<br><b>Sequence log:</b><br>\n"+c:"<br><b>Sequence log:</b> Empty.<br>",
$.MessageBox({buttonFail:"Close",buttonDone:"Refresh",message:e+d+h+c,top:"auto",speed:0}).done(function(){showLoading(!0,1);seqShowLog(a)})):$.MessageBox(b.message||"Error. Try again.")},error:function(a){showLoading(!1,1);$.MessageBox(a.responseText||"Error. Please try again.")}});d.jumpToEnd()})}
function seqRefreshClick(a){sequenceOnScreen.saved?(subscriptionCheck(),seqList()):$.MessageBox({buttonDone:"Discard changes",buttonFail:"Keep editing",message:"You have unsaved changes in the sequence."}).done(function(){subscriptionCheck();seqList()})}
function seqList(a){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return c.yield(getCookies(),2);b=c.yieldResult;showLoading(!0).then(function(){$(".seq_control_btns > *").hide();-1==a&&(a=parseInt($(".sequences tr.seq-active").attr("seq-id")));$(".seq_title").html("Sequences Cloud");$("#seq_create").prop("disabled",!1);showLoading(!0,1).then(function(){Promise.all([$.ajax({url:apiAddress+"getSequences",method:"POST",contentType:"application/json; charset=utf-8",
data:JSON.stringify({cookies:b}),success:function(b){sequenceOnScreen.saved=!0;seqViewClear();window.cloudSequences=b;var c=[],d;for(d in b)c.push(b[d]);c.sort(function(a,b){return a.order-b.order});b=$jscomp.makeIterator(c);for(c=b.next();!c.done;c=b.next())c=c.value,$("table.sequences tbody").append('<tr seq-id="'+c.id+'"><td>'+(c.name||"")+"</td><td>"+c.status+"</td> <td>"+(c.enrolled||0)+'</td><td><input type="number" class="num" min="0" value="'+(c.enrollPerDay||"0")+'"></td><td class="clean"><button tabindex="-1" class="delete" type="button">Delete</button></td></tr>');
$("table.sequences input.num").change(seqEnrollPerDayChange);a&&-1<a&&seqClick({target:$('table.sequences tr[seq-id="'+a+'"]')[0]})},error:function(a){seqViewClear();401==a.status?userLogout(null,!0):0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Error occurred.")}}),$.ajax({url:apiAddress+"getResponses",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:b}),success:function(a){window.cloudResponses=
a&&a.responses||[]},error:function(a){log(a)}})]).then(function(){blList();showLoading(!1,1)}).catch(function(){showLoading(!1,1)})})});c.jumpToEnd()})}function seqViewClear(){$("table.sequences tbody").empty();$(".tab.seq-edit").hide();$(".tab.seq-save").hide();$(".tab.seq-create-step").hide();$(".tab.seq-steps-view").hide()}
function seqEnrollPerDayChange(a){a.preventDefault();var b=parseInt(a.target.value)||0;0>b&&(a.target.value=0);var c=0;$("table.sequences input.num").each(function(b){this!=a.target&&(b=parseInt(this.value)||0,c+=b)});var d=window.loginData&&window.loginData.enrollmentsPerDay||0;b+c>d&&(a.target.value=Math.max(d-c,0),$(a.target).removeClass("pulse"),setTimeout(function(){return $(a.target).addClass("pulse")},0));seqEnrollPerDaySave()}
function seqEnrollPerDaySave(a){var b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return b=0,d.yield(getCookies(),2);c=d.yieldResult;$("table.sequences tr").each(function(a){var e=parseInt($(this).attr("seq-id"));if(e){var d=parseInt($(this).find("input.num").val())||0;window.cloudSequences[e]&&window.cloudSequences[e].enrollPerDay!=d&&$.ajax({url:apiAddress+"setSequenceParameter",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:c,
id:e,enrollPerDay:d}),success:function(a){window.cloudSequences[e].enrollPerDay=d},error:function(a){$.MessageBox(a.responseText||"Unknown Error. Contact support.")}});b+=d}});seqUpdateEnrolledCounter(b,a);d.jumpToEnd()})}function seqCheckEnrolledPerDay(a){a=a||window.loginData&&window.loginData.enrollmentsPerDay;var b=0;$("table.sequences tr input.num").each(function(c){c=parseInt(this.value);a<b+c&&(this.value=Math.max(a-b,0));b+=c});a<b?seqEnrollPerDaySave(a):seqUpdateEnrolledCounter(b,a)}
function seqUpdateEnrolledCounter(a,b){a||(a=0,$("table.sequences tr").each(function(b){parseInt($(this).attr("seq-id"))&&(a+=parseInt($(this).find("input.num").val())||0)}));$("a.enrollments").text(a+" of "+(b||window.loginData.enrollmentsPerDay)).show()}
function seqStop(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return b.yield(getCookies(),2);a=b.yieldResult;$.MessageBox({buttonDone:"Yes",buttonFail:"Cancel",message:"All the progress for the sequence will be lost. Are you sure?",top:"auto"}).done(function(){var b=parseInt($(".sequences tr.seq-active").attr("seq-id"));b&&(showLoading(!0,1),$.ajax({url:apiAddress+"stopSequence",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:a,
id:b}),success:function(a){a&&a.stopped?seqList(b):(showLoading(!1,1),$.MessageBox(a.message||"Error. Try again."))},error:function(a){showLoading(!1,1);$.MessageBox(a.responseText||"Error. Please try again.")}}))});b.jumpToEnd()})}
function seqInit(){seqInitiated||(seqInitiated=!0,log("Initiating relation fields for sequences."),$.get("https://www.linkedin.com/people/invite?from=profile&key=9999",function(a){a=a.replace(/Michael/g,"this person");a=$(a);var b='<select id="seq_rel" class="form-control how-know sel2-ignore">',c="";a.find("#main-options .radio-btn").each(function(){"iweOther"!=$(this).val()&&"dontKnow"!=$(this).val()&&(b="IF"==$(this).val()?b+'<option selected value="'+$(this).val()+'">'+$(this).next().text()+"</option>":
b+'<option value="'+$(this).val()+'">'+$(this).next().text()+"</option>",$(this).next().next().find("select").html()&&($(this).next().next().find("select").find("option").first().remove(),$(this).next().next().find("select").find("option").last().remove(),$(this).next().next().find("select").find('option[value="OTHER"]').remove(),c=c+'<select name="'+$(this).next().next().find("select").attr("name")+'" style="display:none;" class="form-control secondlevel sel2-ignore '+$(this).val()+'" id="'+$(this).val()+
'">'+$(this).next().next().find("select").html()+"</select>"))});b+="</select>";c&&(c+='<select disabled name="existingPositionIF" style="display: none;" class="form-control secondlevel sel2-ignore IF" id="IF">');$("#seq_rel").remove();$("#seq_where").remove();$(".seq-param__rel").append(b);$(".seq-param__where").append(c);$(".how-know").change(function(){$(".secondlevel").hide();$("."+$(this).val()).show().change();$(this).val()}).change();$(".secondlevel").change(function(){}).change();showLoading(!1)}))}
function seqStart(){parseInt($(".sequences tr.seq-active").attr("seq-id"))&&(sequenceOnScreen.saved?seqCloudStart():$.MessageBox("Save the changes first."))}
function seqCloudStart(a){showLoading(!0,1);chrome.runtime.sendMessage({action:"GetCookies"},function(b){$.ajax({url:apiAddress+"startSequence",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({id:sequenceOnScreen.id,currentStatus:sequenceOnScreen.status,cookies:b,force:!!a}),success:function(a){if(a&&a.changed){if(void 0!==a.saveCookies||a.newStatus==seqStatus.ACTIVE)window.saveCookies=a.saveCookies||window.saveCookies,window.hasActiveSequence=a.newStatus==seqStatus.ACTIVE||
window.hasActiveSequence,saveToStorage({saveCookies:window.saveCookies,hasActiveSequence:window.hasActiveSequence});a.message&&$.MessageBox(a.message);seqList(sequenceOnScreen.id)}else a&&!1===a.changed?a.accountChanged?$.MessageBox({buttonDone:"Continue with "+a.newAccount.fullName,buttonFail:"Cancel",buttonsOrder:"fail done",message:a.message}).done(function(){seqCloudStart(!0)}).fail(function(){showLoading(!1,1)}):($.MessageBox(a.message||"Error. Try again."),seqList(sequenceOnScreen.id)):(showLoading(!1,
1),$.MessageBox(a.message||"Error. Try again."))},error:function(a){showLoading(!1,1);$.MessageBox(a.responseText||"Error. Please try again.")}})})}
function seqCreate(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return showLoading(!0,1),b.yield(getCookies(),2);a=b.yieldResult;$.ajax({url:apiAddress+"createSequence",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:a}),success:function(a){seqList(a.newId)},error:function(a){showLoading(!1,1);401==a.status?userLogout(null,!0):0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||
"Error occurred.")}});b.jumpToEnd()})}function seqSave(){$("#seq_urls input").val().trim()?$.MessageBox("Please confirm entered URL by pressing Enter."):seqSaveCurrent()}
function seqSaveCurrent(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return showLoading(!0,1),sequenceOnScreen.name=$(".tab.seq-edit #seq_name").val(),sequenceOnScreen.enrollPerDay=$(".sequences tr.seq-active input.num").val(),b.yield(getCookies(),2);a=b.yieldResult;sequenceOnScreen.urls=[];$(".tab.seq-edit").find("#seq_urls ul a").each(function(a,b){b&&sequenceOnScreen.urls.push({id:b.dataset&&b.dataset.linkId||void 0,link:b.href})});$.ajax({url:apiAddress+
"saveSequence",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:a,sequence:sequenceOnScreen}),success:function(a){a.saved?seqList(sequenceOnScreen.id):($.MessageBox(a.message||"Nothing to save."),showLoading(!1,1))},error:function(a){showLoading(!1,1);401==a.status?userLogout(null,!0):0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Error occurred.")}});b.jumpToEnd()})}
function seqStepSave(a){a.preventDefault();if(a=parseInt($(".sequences tr.seq-active").attr("seq-id"))){var b=$("#seq_step_edit"),c=parseInt(b.find('input[name="step-order"]').val())||0;if(c&&sequenceOnScreen.steps[c-1])sequenceOnScreen.steps[c-1].message=b.find("textarea").val().trim();else{c=parseInt(b.find(".step-edit__days").val())||0;var d=parseInt(b.find(".step-edit__minutes").val())||0;sequenceOnScreen.steps.push({seq_id:a,message:b.find("textarea").val().trim(),delayDays:0>c?0:c,delayMinutes:0>
d?0:d,order:parseInt(b.find('input[name="step-order"]').val())||"",type:b.prop("data-type")||""})}sequenceOnScreen.saved=!1;b.hide();seqDisplay({steps:!0})}}function findMaxProp(a,b){var c=void 0;a.forEach&&a.forEach(function(a){void 0!==a[b]&&(void 0===c||a[b]>c)&&(c=a[b])});return c}function seqStepsCleanView(){$(".tab.seq-steps-view > .steps").empty()}
function seqStepCreateClickHandler(a){if(parseInt($(".sequences tr.seq-active").attr("seq-id"))){a=$(a.target).hasClass("seq_connect")?stepType.CONNECT:stepType.MESSAGE;var b=$(".step.connect, .step.message").length;b<MAX_STEPS_COUNT?seqStepEditPopup({delayDays:10,delayMinutes:0,type:a,title:"Step "+(b+1)+" - "+a,subject:"",message:"",order:b+1,new:!0}):$.MessageBox("Sorry, no more than "+MAX_STEPS_COUNT+" steps per sequence is allowed.")}}
function seqAddLink(){var a=$("#seq_urls input").val().trim();-1!=a.indexOf("linkedin.com/search/results/people/")||-1!=a.indexOf("linkedin.com/sales/search")?(sequenceOnScreen.saved=!1,a=a.replace(/"/g,"%22"),$("#seq_urls ul").append('<li class="seq-urls__item"><span class="seq-urls__item__delete" title="delete"></span><a target="_blank" href="'+a+'">'+a+"</li>"),$("#seq_urls input").val("")):$.MessageBox('Entered URL is neither <a target="_blank" href="https://www.linkedin.com/search/results/people/">LinkedIn Search URL</a> nor <a href="https://www.linkedin.com/sales/search" target="_blank">Sales Navigator URL</a>.')}
function seqStepChange(a){sequenceOnScreen.saved=!1;var b=$(a.target).closest(".step").prev();b=parseInt(b.attr("data-step-order"))||0;"number"==a.target.type?a.target.classList.contains("days")?sequenceOnScreen.steps[b-1].delayDays=a.target.value:sequenceOnScreen.steps[b-1].delayMinutes=a.target.value:"checkbox"==a.target.type&&(sequenceOnScreen.steps[b-1].delayType=a.target.checked?delayTypes.ACCEPTED:delayTypes.DAYS)}
function seqStepClick(a){var b=$(a.target).closest(".step"),c=parseInt(b.attr("data-step-id")),d=parseInt(b.attr("data-step-order"))||0;$(".seq-steps-view .step.connect, .seq-steps-view .step.message");"delete"==a.target.dataset.role?$('[data-step-id="'+c+'"]').slideUp(200).promise().done(function(){sequenceOnScreen.saved=!1;sequenceOnScreen.steps.splice([d-1],1);seqDisplay({steps:!0})}):"edit"==a.target.dataset.role&&seqStepEditPopup({id:c,message:b.find(".step__content")[0].innerText,delay:b.next().find(".step__next .num").val(),
title:b.find(".step__head_name").text(),order:d,type:b.hasClass("connect")?stepType.CONNECT:stepType.MESSAGE})}
function seqStepEditPopup(a){var b=$("#seq_step_edit");b.prop("data-type",a.type||"");b.find(".step-edit__subject input").val(a.subject||"");b.find(".heading").text(a.title||"");b.find("textarea").val(a.message||"");b.find("textarea").prop("maxlength",a.type==stepType.CONNECT?MAX_CONNECT_MSG_SIZE:9999);b.find(".step-edit__days").val(a.delayDays||"");b.find(".step-edit__minutes").val(a.delayMinutes||"");b.find('input[name="step-id"]').val(a.id||"");b.find('input[name="step-order"]').val(a.order||"");
b.find('input[name="step-new"]').val(a.new?"1":"");b.find("#seq_edit_save").html(a.new?"Add":"Save");b.fadeIn(200)}
function seqClick(a){var b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return b=$(a.target),c=parseInt(b.closest("tr").attr("seq-id")),e.yield(getCookies(),2);d=e.yieldResult;if(b.hasClass("delete"))$.MessageBox({buttonDone:"Yes",buttonFail:"Cancel",message:"Are you sure you want to delete the sequence?",top:"auto"}).done(function(){log("Delete a sequence");c?(showLoading(!0,1),$.ajax({url:apiAddress+"deleteSequence",method:"POST",contentType:"application/json; charset=utf-8",
data:JSON.stringify({cookies:d,id:c}),success:function(a){a.deleted?seqList(sequenceOnScreen.id):($.MessageBox(a.message||"Sorry, cannot delete."),showLoading(!1,1))},error:function(a){showLoading(!1,1);401==a.status?userLogout(null,!0):0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Error occurred.")}})):log("Bad sequence id: "+c)});else if(!b.hasClass("clean")&&!b.hasClass("num")&&a&&a.target&&"A"!=a.target.nodeName)c&&(sequenceOnScreen.saved?
seqDisplayById(c):$.MessageBox({buttonDone:"Discard changes",buttonFail:"Keep editing",message:"You have unsaved changes in the sequence."}).done(function(){seqDisplayById(c)}));else return e.return(!0);e.jumpToEnd()})}
function seqDisplayById(a){$(".sequences tr.seq-active").removeClass("seq-active");$(".sequences tr[seq-id="+a+"]").addClass("seq-active");$(".tab.seq-edit").hide();$(".tab.seq-create-step").hide();$(".tab.seq-steps-view").hide();cloudSequences[a]&&(a=cloudSequences[a],sequenceOnScreen.saved=!0,sequenceOnScreen.id=a.id,sequenceOnScreen.status=a.status,sequenceOnScreen.name=a.name,sequenceOnScreen.urls=Object.assign([],a.urls),sequenceOnScreen.steps=Object.assign([],a.steps),seqDisplay())}
function seqDisplay(a){if(!a||a.main){$(".seq_control_btns > a").show();$("#seq_start").show();var b=$(".tab.seq-edit");switch(sequenceOnScreen.status){case seqStatus.ACTIVE:$("#seq_start").text("Pause").prop("disabled",!1);break;case seqStatus.PAUSED:case seqStatus.ERROR:$("#seq_start").text("Continue").prop("disabled",!1);break;case seqStatus.COMPLETE:$("#seq_start").text("Pause").prop("disabled",!0);break;default:$("#seq_start").text("Start").prop("disabled",!1)}sequenceOnScreen.status==seqStatus.NOT_STARTED?
(b.find("style").html(""),b.find("input").not(".disabled").prop("disabled",!1),b.find("select").prop("disabled",!1),b.find("button").prop("disabled",!1),$(".tab.seq-steps-view button").prop("disabled",!1),$("#seq_stop").hide()):(b.find("style").html(".seq-urls__item.link-active .seq-urls__item__delete {display: none;} #seq_stop {display: inline-block;}"),$("#seq_stop").show());b.find("#seq_name").val(sequenceOnScreen.name)}if(!a||a.links)b.find("#seq_urls ul").empty(),b.find("#seq_urls input").val(""),
sequenceOnScreen.urls.forEach(function(a){var c=a.status==seqStatus.NOT_STARTED?"":" link-active";b.find("#seq_urls ul").append('<li class="seq-urls__item'+c+'"><span class="seq-urls__item__delete" title="delete"></span><a target="_blank" data-link-id="'+a.id+'" href="'+a.link+'">'+a.link+"</a></li>")}),b.show(),$(".tab.seq-save").show();if(!a||a.steps){var c=$(".tab.seq-steps-view .steps");c.empty();var d=1;sequenceOnScreen.steps.forEach(function(a){a.order=d++;var b='<div class="step '+a.type.toLowerCase()+
' line-left-v" '+(a.id?'data-step-id="'+a.id+'"':"")+' data-step-order="'+a.order+'"><div class="step__head '+a.type.toLowerCase()+' line-left-h"><span class="step__head_name">Step '+a.order+" - "+a.type+'</span><span class="step__head-control"><img title="Edit step" data-role="edit" src="../img/pencil.png"/><img title="Delete step" data-role="delete" src="../img/close2.png"/></span></div><div class="step__content">'+a.message.replace(/\n/g,"<br>")+'</div></div><div class="step delay line-left-v" data-step-id="'+
(a.id||"")+'"><div class="step__head delay line-left-h"><span class="step__head_name">Delay</span></div><div class="step__next">'+(a.type==stepType.CONNECT?"Once connect is accepted wait ":"If no response after ")+'<span><input type="number" class="num days" min="0" value="'+a.delayDays+'"> days and <span><input type="number" class="num minutes" min="0" value="'+a.delayMinutes+'"> minutes</span></div></div>';c.append(b);a.delayType=a.delayType||delayTypes.DAYS;c.find('>.step[data-step-order="'+a.order+
'"] +.delay .step__next input[type="checkbox"]').prop("checked",a.delayType==delayTypes.ACCEPTED)});sequenceOnScreen.steps.length?($(".seq-create-step").hide(),$(".seq-steps-view").show()):($(".seq-create-step").show(),$(".seq-steps-view").hide())}}$(window).on("beforeunload",function(a){if(!sequenceOnScreen.saved&&sequenceOnScreen.id)return a.returnValue="You have unsaved sequence. Are you sure to leave?"});function seqMarkUnsaved(){sequenceOnScreen.saved=!1}
function seqStepInsertHtml(a){var b='<div class="step '+a.type.toLowerCase()+' line-left-v" '+(a.id?'data-step-id="'+a.id+'"':"")+' data-step-order="'+a.order+'"><div class="step__head '+a.type.toLowerCase()+' line-left-h"><span class="step__head_name">Step '+a.order+" - "+a.type+'</span><span class="step__head-control"><img title="Edit step" data-role="edit" src="../img/pencil.png"/><img title="Delete step" data-role="delete" src="../img/close2.png"/></span></div><div class="step__content">'+a.message.replace(/\n/g,
"<br>")+'</div></div><div class="step delay line-left-v" data-step-id="'+a.id+'"><div class="step__head delay line-left-h"><span class="step__head_name">Delay</span></div><div class="step__next">Wait for <span><input type="number" class="num" min="0" value="'+a.delay+'"> days</span>'+(a.type==stepType.CONNECT?'<label class="skip-delay"><input type="checkbox">Skip if connection is accepted</label>':"")+"</div></div>",c=$(".tab.seq-steps-view .steps");if(a.new)c.append(b);else{var d=c.find('>.step[data-step-id="'+
a.id+'"]:first');if(0==d.length)return;a.type==stepType.CONNECT&&(a.delayType=d.next().find("select").val());var e=d.prev();0<e.length?e.after(b):c.prepend(b);d.next().remove();d.remove()}a.delayType=a.delayType||delayTypes.DAYS;c.find('>.step[data-step-id="'+a.id+'"] .step__next input[type="checkbox"]').prop("checked",a.delayType==delayTypes.ACCEPTED);$(".seq-create-step").hide();$(".seq-steps-view").show()}
function subscriptionCheck(a){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){if(!window.loginData.email)return $(".tab.plans").hide(),showLoading(!1),c.return();b=isPageActive(0)||isPageActive(6)||a&&a.target&&"prospects_remain"==a.target.id;return c.yield(getCookies(),2)}b&&showLoading(!0);chrome.runtime.sendMessage({action:"GetCookies"},function(a){Promise.all([plansInitiated||$.ajax({url:apiAddress+"plans?ver=last",method:"GET",success:function(a){a.width&&
$(".tab.plans").css("min-width",a.width);var b=$(".tab.plans .row").first();b.empty();a.plans&&a.plans.forEach&&(a.plans.forEach(function(a){var c="";c+='<div class="prospect"><div class="prospect__title" style="border-top-color:'+a.color+';"><h6 class="prospect__name">'+a.title+'</h6><h3 class="prospect__price">$'+a.price+'</h3></div><ul class="prospect__features">';a.features.forEach(function(a){c+='<li class="prospect__feature'+(a.disabled?" is-disabled":"")+'">'+a.title+"</li>\n"});c+='</ul>\n<button class="prospect__btn" data-plan="'+
a.name+'" style="background-color:'+a.color+';"><span></span></button>\n</div>';b.append(c)}),plansInitiated=!0)},error:function(a){}}),$.ajax({url:apiAddress+"checkSubscription2",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:a}),error:function(a){401==a.status?userLogout(null,!0):0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Error occurred.")}})]).then(function(a){b&&showLoading(!1);a=$jscomp.makeIterator(a);
a.next();a=(a=a.next().value)||{};showNews(a.news);void 0!==a.saveCookies&&(window.saveCookies=a.saveCookies,saveToStorage({saveCookies:a.saveCookies}));window.loginData=Object.assign(window.loginData,a);window.loginData.subscription=a.subscription&&a.subscription.plan?a.subscription:{};seqCheckEnrolledPerDay(a.enrollmentsPerDay);window.loginData.enrollmentsPerMonth=a.enrollmentsPerMonth;window.loginData.enrollmentsPerDay=a.enrollmentsPerDay;window.loginData.signUpUrl=a.signUpUrl;window.loginData.sequencesCloudEnabled=
a.sequencesCloudEnabled;window.loginData.sequencesNewEnabled=a.sequencesNewEnabled;window.loginData.oldSequencesEnabled=a.oldSequencesEnabled;window.loginData.intercomHash=a.intercomHash;window.loginData.billingData=a.billingData;saveToStorage({loginData:window.loginData},function(){showSubscription();showUser()});void 0!==a.enrolled&&void 0!==a.enrollmentsPerDay?$("#prospects_remain").html(a.enrolled+" of "+a.enrollmentsPerDay+" Enrolled"):$("#prospects_remain").html("0 of 0 Enrolled")}).catch(function(a){b&&
showLoading(!1);$("#prospects_remain").html("0 of 0 Enrolled")})});c.jumpToEnd()})}
function showSubscription(){$(".prospect__btn span").html("");$("table.payment-hist tbody").html("");$(".tab.plans .prospect__btn").removeClass("is-active upgrade downgrade");$(".plans .prospect__btn").off("click");var a=window.loginData.billingData||{};if(a.plan)for(var b="downgrade",c=$(".tab.plans .prospect__btn"),d=0;d<c.length;d++)c[d].dataset.plan==window.loginData.billingData.plan?($(c[d]).addClass("is-active").find("span").html(window.loginData.billingData.planExtraInfo||""),b="upgrade"):
$(c[d]).addClass(b);else $('.tab.plans .prospect__btn[data-plan="free"]').addClass("is-active");a.cardLast4&&$(".tab.payment-details .card").html("**** **** **** "+a.cardLast4);if(a.invoices&&a.invoices.length)for(b=0;b<a.invoices.length;b++)c=a.invoices[b],$("table.payment-hist tbody").append("<tr><td>"+$.format.date(new Date(1E3*c.date),"MMM dd, yyyy")+(c.type?" "+c.type:"")+"</td><td>$"+c.amount/100+"</td>"+(c.link?'<td><a target="_blank" href="'+c.link+'">View</td>':"")+"</tr>");$(".plans .prospect__btn.upgrade, .plans .prospect__btn.downgrade").click(subscribe);
$("#form-add-card").attr("action",apiAddress+"billing.html");$('#form-add-card [name="extensionId"]').val(chrome.runtime.id);$(".tab.payment-details").show();$(".tab.payment-history").show()}
function updateCard(a){var b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return a.preventDefault(),showLoading(!0),e.yield(getCookies(),2);b=e.yieldResult;c=(b.match('li_at="?([^"]+?)"?;')||[])[0]||"";d=(b.match('JSESSIONID="?([^"]+?)"?;')||[])[0]||"";$('#form-add-card [name="action"]').val("updatecard");$('#form-add-card [name="cookies"]').val(c+" "+d);$("#form-add-card").append('<input type="hidden" name="redirect" value="'+window.location+'">');$("#form-add-card").submit();
e.jumpToEnd()})}
function subscribe(a){var b,c,d,e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){if(1==g.nextAddress){if(!window.loginData||!window.loginData.email)return $.MessageBox("Please log in.").done(function(){pageSelect("page0")}),g.return();b=a.target.dataset.plan;c=$(a.target).hasClass("upgrade");return g.yield(getCookies(),2)}d=g.yieldResult;if(!window.loginData.billingData||!window.loginData.billingData.cardLast4&&"free"!=b)return showLoading(!0),e=(d.match('li_at="?([^"]+?)"?;')||[])[0]||
"",f=(d.match('JSESSIONID="?([^"]+?)"?;')||[])[0]||"",$('#form-add-card [name="action"]').val("addcard&subscribe"),$('#form-add-card [name="cookies"]').val(e+" "+f),$("#form-add-card").append('<input type="hidden" name="plan" value="'+b+'">'),$("#form-add-card").append('<input type="hidden" name="redirect" value="'+window.location+'">'),$("#form-add-card").submit(),g.return();$.MessageBox({buttonDone:"Yes",buttonFail:"Cancel",message:c?"You are going to upgrade your plan.<br>You will be charged for the difference. Continue?":
"You are going to downgrade your plan.<br>You will be able to use the current plan till the end of the month. Continue?"}).done(function(){showLoading(!0);$.ajax({url:apiAddress+"billing",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:d,plan:b,action:"subscribe"}),success:function(a){subscriptionCheck()},error:function(a){showLoading(!1);0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Error occurred.").done(function(){401==
a.status&&window.location.reload()})}})});g.jumpToEnd()})}function userLogout(a,b){a&&a.preventDefault&&a.preventDefault();window.Intercom&&window.Intercom("boot",{app_id:"ajlejzmy"});window.loginData={};saveToStorage({loginData:{}},function(){b&&(window.location.hash="#page0");window.location.reload()})}
function userSignin(a){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return a.preventDefault(),$("#li_login img").attr("src","img/sloading.svg"),c.yield(getCookies(),2);b=c.yieldResult;$.ajax({url:apiAddress+"signin",method:"POST",contentType:"application/json",data:JSON.stringify({cookies:b}),success:function(a){try{a=JSON.parse(a)}catch(e){}a.email&&saveToStorage({loginData:a},function(){window.location.reload()})},error:function(a){$("#li_login img").attr("src",
"img/icons/linkedin32.png");0==a.readyState?$.MessageBox("Network error. Cannot connect to the server."):$.MessageBox(a.responseText||"Unknown error. Please contact support.")}});c.jumpToEnd()})}
function hashChangedHandler(a){a=window.location.hash.slice(1);window.loginData.email&&a||(a="page0");$(".page").hide();$(".nav-block__item.is-active").removeClass("is-active");$('.nav-block__item [data-for="'+a+'"]').parent().addClass("is-active");$("#"+a).show();"page1"==a&&seqList();a=pageProperties[a]&&pageProperties[a].title||"LinkedHub";$("title").text(a)}
function pageSelect(a){if(a&&a.target&&a.target.attributes){var b=a.target.attributes["data-for"].value;a.preventDefault()}else if("string"==typeof a)b=a;else return;document.location.hash!="#"+b?document.location.hash="#"+b:hashChangedHandler()}function showLoading(a,b){var c=$.Deferred();b&&!isPageActive(b)?c.resolve():a?$("#loading").fadeIn(200,function(){c.resolve()}):$("#loading").fadeOut(200,function(){c.resolve()});return c}
function isPageActive(a){return window.location.hash=="#page"+a||0==a&&!window.location.hash}
function blList(a){$(".blacklist tbody").empty();window.cloudResponses&&(window.cloudResponses.forEach(function(a){var b='<a target="_blank" href="'+a.profile_link+'">Profile</a>';a.thread_id&&(b+=' | <a target="_blank" href="https://www.linkedin.com/messaging/thread/'+a.thread_id+'">Conversation</a>');$("table.blacklist tbody").prepend('<tr bl-id="'+a.id+'"><td>'+(a.first_name||"")+"</td><td>"+(a.last_name||"")+"</td> <td>"+b+'</td><td><button class="delete" type="button">Delete</button></td></tr>')}),
blFilterExec(a))}function blClick(a){a=$(a.target);var b=parseInt(a.closest("tr").attr("bl-id"));a.hasClass("delete")&&deleteResponseCloud(b,a)}
function deleteResponseCloud(a,b){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return b&&b.hide(),d.yield(getCookies(),2);c=d.yieldResult;$.ajax({url:apiAddress+"deleteResponse",method:"POST",contentType:"application/json; charset=utf-8",data:JSON.stringify({cookies:c,id:a}),success:function(a){b&&b.closest("tr").remove()},error:function(a){log(a);b&&(b.show(),$.MessageBox("Cannot delete the entry."))}});d.jumpToEnd()})}
function blFilterChange(a){log("blacklist filter");blFilterTimer&&clearTimeout(blFilterTimer);blFilterTimer=setTimeout(blFilterExec.bind(this,!0),400)}function blFilterExec(a){log("filter");if(a=$(".bl-filter input").val().trim().replace(/[\/\\\(\\)]/g,"")){var b=new RegExp(a,"i");$(".blacklist tbody tr").each(function(a,d){$(d).find("td:nth-child(1),td:nth-child(2)").text().match(b)?$(d).show():$(d).hide()})}else $(".blacklist tbody tr").show()}
function showSmallPopup(){$("#quick_message").fadeIn(100);setTimeout(function(){$("#quick_message").fadeOut(500)},1E3)}function getCookies(a){a=void 0===a?"https://www.linkedin.com":a;return new Promise(function(b){chrome.cookies.getAll({url:a},function(a){a=a||[];var c="";a.forEach(function(a){a.name&&a.value&&(c+=a.name+"="+a.value+"; ")});b(c)})})}
function showNews(a){if(a&&a.sequences&&a.sequences.id&&a.sequences.html){var b={},c="news_seen_"+a.sequences.id;b[c]=!1;loadFromStorage(b,function(d){d[c]||($("#page1 > .news .info-container").html(a.sequences.html),$("#page1 > .news").slideDown(200),$('#page1 > .news button[action="ok"]').click(function(a){$("#page1 > .news").slideUp(200);b[c]=!0;saveToStorage(b)}))})}};